# Author: Rahul Yadav
- name: Install's docker-ce, docker-compose on configured nodes.
  hosts: localhost
  remote_user: ec2-user
  become: true

  vars:
    DOCKER_COMPOSE_VERSION: "v2.2.2"

  tasks:
    - name: Updates & Upgrade Yum Package
      yum:
        update_only: yes

    - name: Installing using amazon-linux-extras package
      yum:
        name: amazon-linux-extras

    - name: Install docker
      yum:
        name: docker
        state: latest


    # - name: Confirm Docker Installation
    #   command: service docker status

    # If fails post this step, --start-task-at="<next step>"
    - name: Start the docker service
      ansible.builtin.service:
        name: docker
        state: started

    # Logout post running this command to be able to run docker commands as ec2-user.
    - name: Adding current user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: 'docker'
        append: True

    - name: Get Os Name
      command: uname -s
      register: os_version

    - name: Get OS Arch
      command: uname -m
      register: os_arch

    - name: Installing Docker Compose
      # Module Doc: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#ansible-collections-ansible-builtin-get-url-module
      # Compose Version: https://github.com/docker/compose/releases
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-{{ os_version.stdout }}-{{ os_arch.stdout }}
        dest: /usr/local/bin/docker-compose
        mode: 'u=rxw,g=x,o=x'
        owner: ec2-user
